name: Deploy main

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_BACKEND: ${{ secrets.BACKEND }}
          envkey_SENDINBLUE_SECRET: ${{ secrets.SENDINBLUE_SECRET }}

      - name: Build the Docker image
        run: docker build -t ghcr.io/${{ secrets.IMAGE_REPOSITORY }}/${{ secrets.IMAGE_NAME }}:latest-main .

      - name: Login to ghcr
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push the Docker image
        run: docker push ghcr.io/${{ secrets.IMAGE_REPOSITORY }}/${{ secrets.IMAGE_NAME }}:latest-main

      - name: Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSHHOST }}
          username: ${{ secrets.SSHUSER }}
          key: ${{ secrets.SSHKEY }}
          passphrase: ${{ secrets.SSHPASS }}
          script: |
            docker login --username=${{ github.actor }} --password=${{ secrets.GITHUB_TOKEN }} ghcr.io
            docker pull ghcr.io/${{ secrets.IMAGE_REPOSITORY }}/${{ secrets.IMAGE_NAME }}:latest-main
            docker stop 1001n-main
            docker rm 1001n-main
            docker run -d -p 49165:3000 --name=1001n-main --restart=always --pull=always ghcr.io/${{ secrets.IMAGE_REPOSITORY }}/${{ secrets.IMAGE_NAME }}:latest-main
            docker system prune -f
