name: Deploy main

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_BACKEND: ${{ secrets.BACKEND }}
          envkey_SENDINBLUE_SECRET: ${{ secrets.SENDINBLUE_SECRET }}

      - name: Build the Docker image
        run: docker build -t cloud.canister.io:5000/vkluchenkov/1001n:latest-main .

      - name: Login to Canister
        uses: docker/login-action@v2
        with:
          registry: cloud.canister.io:5000
          username: ${{ secrets.CANISTERLOGIN }}
          password: ${{ secrets.CANISTERPASS }}

      - name: Push the Docker image
        run: docker push cloud.canister.io:5000/vkluchenkov/1001n:latest-main

      - name: Deploy
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SSHHOST }}
          username: ${{ secrets.SSHUSER }}
          key: ${{ secrets.SSHKEY }}
          passphrase: ${{ secrets.SSHPASS }}
          script: |
            docker login --username=${{ secrets.CANISTERLOGIN }} --password=${{ secrets.CANISTERPASS }} cloud.canister.io:5000
            docker pull cloud.canister.io:5000/vkluchenkov/1001n:latest-main
            docker stop 1001n-main
            docker rm 1001n-main
            docker run -d -p 49165:3000 --name=1001n-main --restart=always --pull=always cloud.canister.io:5000/vkluchenkov/1001n:latest-main
            docker system prune -f
