name: Deploy dev

on:
  push:
    branches: ['dev']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_BACKEND: ${{ secrets.BACKEND }}
          envkey_SENDINBLUE_SECRET: ${{ secrets.SENDINBLUE_SECRET }}

      - name: Build the Docker image
        run: docker build -t ghcr.io/${{ secrets.IMAGE_REPOSITORY }}/${{ secrets.IMAGE_NAME }}:latest-dev .

      - name: Login to ghcr
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push the Docker image
        run: docker push ghcr.io/${{ secrets.IMAGE_REPOSITORY }}/${{ secrets.IMAGE_NAME }}:latest-dev

      - name: Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSHHOST }}
          username: ${{ secrets.SSHUSER }}
          key: ${{ secrets.SSHKEY }}
          passphrase: ${{ secrets.SSHPASS }}
          script: |
            docker login --username=${{ github.actor }} --password=${{ secrets.GITHUB_TOKEN }} ghcr.io
            docker pull ghcr.io/${{ secrets.IMAGE_REPOSITORY }}/${{ secrets.IMAGE_NAME }}:latest-dev
            docker stop 1001n-dev
            docker rm 1001n-dev
            docker run -d -p 49164:3000 --name=1001n-dev --restart=always --pull=always ghcr.io/${{ secrets.IMAGE_REPOSITORY }}/${{ secrets.IMAGE_NAME }}:latest-dev
            docker system prune -f
